### ISSUE TITLE
Ausführung des Workflows ab Punkt (Stelle die Tabellenblätter-Namen als Liste dar und lasse ein Tabellenblatt daraus auswählen)

### ISSUE THREAD

**Issue by togotom** [lka/excel2zugferd#10]
- Stelle die Tabellenblätter-Namen als Liste dar und lasse ein Tabellenblatt daraus auswählen.
- Lies die Daten des ausgewählten Tabellenblattes ein und erstelle daraus ein PDF.
- Hänge an das PDF das ZugFeRD Konstrukt im XML-Format an.
- Speichere die Datei als Tabellenblatt-Name.pdf im Verzeichnis der ausgewählten Excel-Datei.

Was ist mit diesem Punkt gemeint ? Muss man innerhalb Excel das ganze durchführen ?
Wenn ich das Programm Excel2ZugFeRD gestartet und das Excel Dokument TestRechnung.xlsx öffne bekomme ich
die drei Tabellenblätter "Tabelle1, Rechnung2 und Rechnung für Kleinunternehmen" als Liste im Fenster angezeigt.
Ausser Beenden und Speichern habe ich keine Möglichkeit irgendetwas in dem Programm Excel2ZugFeRD zu steuern.
Die ini Datei mit der Mandanten Konfig wurde erfolgreich durchgeführt.

**Comment by lka** [comment]
﻿Nein, nicht innerhalb von Excel.Die Liste zeigt, was das Programm selbst machen soll.Für den Benutzer:In der Auswahl wird das Tabellenblatt ausgewählt, aus dem die Rechnung erstellt werden soll. Hier also Rechnung2, entweder Doppelklick darauf oder auswählen und speichern drücken erstellt die Rechnung. Das wird mit einem PopUp Fenster „Datei …Rechnung2.pdf erstellt“ bestätigt. Wenn nichts passiert, besteht ein Problem mit den Stammdaten.Mit freundlichen GrüßenHerbert LischkaMit freundlichen GrüßenHerbert LischkaAm 17.11.2024 um 13:51 schrieb togotom ***@***.***>:﻿

Stelle die Tabellenblätter-Namen als Liste dar und lasse ein Tabellenblatt daraus auswählen.
Lies die Daten des ausgewählten Tabellenblattes ein und erstelle daraus ein PDF.
Hänge an das PDF das ZugFeRD Konstrukt im XML-Format an.
Speichere die Datei als Tabellenblatt-Name.pdf im Verzeichnis der ausgewählten Excel-Datei.

Was ist mit diesem Punkt gemeint ? Muss man innerhalb Excel das ganze durchführen ?
Wenn ich das Programm Excel2ZugFeRD gestartet und das Excel Dokument TestRechnung.xlsx öffne bekomme ich
die drei Tabellenblätter "Tabelle1, Rechnung2 und Rechnung für Kleinunternehmen" als Liste im Fenster angezeigt.
Ausser Beenden und Speichern habe ich keine Möglichkeit irgendetwas in dem Programm Excel2ZugFeRD zu steuern.
Die ini Datei mit der Mandanten Konfig wurde erfolgreich durchgeführt.

**Comment by togotom** [comment]
Seltsam das mit den Stammdaten hatte ich auch schon mit dem Tip aus Excel Howto #6 versucht
es spielt keine Rolle mit oder ohne ":" es wird kein PDF erstellt egal was ich klicke oder speichere
installiert hate ich die beueste Version v.0.9.0
Das ganze läuft unter einer Hyper-V VM Windows 11 10.0.26100.2448
Office ist in der Version 2024 LTSV Professional Plus installiert

**Comment by lka** [comment]
Was steht in der config.ini ?

**Comment by togotom** [comment]
{
    "Abspann": "Mit freundlichen Grüßen\nThomas Prangenberg",
    "Anschrift": "Firma UG",
    "Betriebsbezeichnung": "Firma UG",
    "Bundesland": "Nordrhein-Westfalen",
    "GiroCode": "Nein",
    "Kleinunternehmen": "Nein",
    "Kontakt": "Tel.: +xxxx\nE-Mail: tom.use@gmx.de",
    "Konto": "Kölner Bank eG\nIBAN: DE55 xxxx xxxx xxxx xxxx xx\nBIC: GENODED1CGN",
    "Name": "Firma UG",
    "Umsatzsteuer": "19",
    "Verzeichnis": "C:/Test/Dokumente",
    "Zahlungsziel": "14",
    "ZugFeRD": "Ja"
}

**Comment by lka** [comment]
1. Anschrift: bitte min. 3 Zeilen
Name
Musterst. 12
12345 Musterstadt

2. Umsatzsteuer: 2 Zeilen
Steuernummer: 12345/12345
Finanzamt Musterstadt

siehe Readme

**Comment by togotom** [comment]
Das wars, die drei Änderungen habe ich testweise übernommen und auf meine Befürfnisse angepasst und jetzt klappt auch der Export entweder mit Button Speichern oder Doppleklick auf das Tabellenblatt.
Vielen Dank für die schnelle  Unterstützung und noch ein schönes Rest WE

**Comment by lka** [comment]
Ich denke, ich baue noch ein paar Prüfroutinen ein, mit Ausgabe für den Benutzer.

**Comment by lka** [comment]
Done

**Comment by togotom** [comment]
Wenn man sich genau an den Screenshot unter ihrer Anleitung halten würde, hätte es ja auch funktioniert, aber eine Syntax Kontrolle währe für den Anwender hilfreich bei der Eingabe.
