### ISSUE TITLE
Formatierung der Spalte "Anzahl" mit Trennzeichen "Komma" anstatt "Punkt" bei Dezimalwerten

### ISSUE THREAD

**Issue by HansRoulade** [lka/excel2zugferd#18]
Übergeht man die ganzzahlige Formatierung der `Anzahl`-Spalte in der Excel-Rechnungsvorlage, so wird sowohl in der generierten PDF als auch in der XML ein Punkt als Trennzeichen verwendet - im Gegensatz zur Währungsformatierung. Diese gemischte Notation ist zumindest dann irreführend, wenn bei Währungen der Punkt als Tausender-Trennzeichen sichtbar wird. Sinnvoll ist die Annahme von Dezimalwerten beispielsweise bei Abrechnung von halben Stunden (anstatt wie in der Vorlage drei Posten à 10min abzurechnen).

**Comment by HansRoulade** [comment]
Sowohl Ultramarin Viewer als auch die Sichtkopie von portinvoice.com zeigen nach wie vor die Formatierung mit Punkt an. Ist das eine Limitierung der Anzeigetools?

**Comment by lka** [comment]
Die Sichtkopie bei portinvoice und Ultramarin Viewer zeigen die XML Daten an, die auf amerikanischer Notation basieren. Die Anzeige mit Komma ist auf die Daten innerhalb des PDF beschränkt.Mit freundlichen GrüßenHerbert LischkaAm 02.01.2025 um 14:43 schrieb HansRoulade ***@***.***>:﻿
Sowohl Ultramarin Viewer als auch die Sichtkopie von portinvoice.com zeigen nach wie vor die Formatierung mit Punkt an. Ist das eine Limitierung der Anzeigetools?
