### ISSUE TITLE
Stammdatenanlage erzeugt Fehler

### ISSUE THREAD

**Issue by Zugchaser** [lka/excel2zugferd#20]
**Describe the bug**
Bei Strasse Hausnummer Absatz PLZ Ort kommt die Fehlermeldung Fehler in den Stammdaten. Anschrift mindestens 3, maximal 5 Zeilen. missverständlich geht es dann weiter Adresszeile 1 Adresszudüsarz optional Adresszeile optional. Mit dem Format was ich eingegeben habe, auch eine dreizeilige oder einzeile Adresse hat diese Fehlermeldung.

**To Reproduce**

**Expected behavior**
Bei einer Eingabe einer zweizeiligen Adresse keine Fehlermeldung danke

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11] win11 23 h2
 - Version [e.g. 23H2]

**Additional context**

**Comment by lka** [comment]
Kann ich bitte die Datei config.ini sehen, bei der diese Fehlermeldung kommt?
Sie ist unter C:\Users\BENUTZERNAME\AppData\Roaming\excel2zugferd zu finden.

**Comment by Zugchaser** [comment]
Hallo,

in dem Verzeichnis befindet sich nur das Logo, das ich in dem Fenster 
hochgeladen haben. Eine Config.ini ist nicht zu finden.
Die Zip-Datei wurde entpackt, dann die Exe gestartet. Vielen Dank für 
die zugige Antwort, ich finde es excellent, das sich jemand dieses 
Themas so annimmt. Viel Erfolg weiterhin und für weitere Fragen stehe 
ich zur Verfügung.
Hier noch der Screenshot....

------ Originalnachricht ------
Von "lka" ***@***.***>
An "lka/excel2zugferd" ***@***.***>
Cc "Zugchaser" ***@***.***>; "Author" 
***@***.***>
Datum 27.12.2024 15:34:51
Betreff Re: [lka/excel2zugferd] Stammdatenanlage erzeugt Fehler (Issue 
#20)

**Comment by lka** [comment]
Der Screenshot ist nicht sichtbar?

**Comment by Zugchaser** [comment]
Hallo guten Morgen, hier nun als Anhang und nicht als eingebette Mail. 
Einen schönen Tag noch..
Viele Grüße



------ Originalnachricht ------
Von "lka" ***@***.***>
An "lka/excel2zugferd" ***@***.***>
Cc "Zugchaser" ***@***.***>; "Author" 
***@***.***>
Datum 27.12.2024 19:45:19
Betreff Re: [lka/excel2zugferd] Stammdatenanlage erzeugt Fehler (Issue 
#20)

**Comment by lka** [comment]
Der Anhang wurde nicht mitgeschickt.
PS. Im Readme auf Github ist ein Beispiel für die erwarteten Eingaben für die Stammdaten.

**Comment by Zugchaser** [comment]
![Screenshot 2024-12-28 164403](https://github.com/user-attachments/assets/e54316a8-a4e9-47c1-a2fe-345daf59cf5a)
![EXCELXML](https://github.com/user-attachments/assets/5886edfd-713b-4b7a-8397-12ba513f43d2)
Hinweis im Readme ist die Darstellung hilfreich nun hängt es aber am Kontakt. Die Bezeichnungen Beschreibung sowie Anschrift und Name sind für ein Unternehmen nicht eindeutig zu mal wenn da immer das gleiche drin stehen soll. Auch die Fehlermeldungen signalisieren eigentlich das ein zweizeiliges Kontaktfeld ok. wäre ist es aber nicht ein dreizeiiliges tut auch nicht.
Danke dem Autor für die promte Antworten.

**Comment by HansRoulade** [comment]
Der Parser für die Formulardaten arbeitet in engen Toleranzgrenzen - die Angaben `Tel.:` und `Email:` müssen in exakt dieser Schreibweise angegeben sein.

**Comment by Zugchaser** [comment]
Das wäre gut zu wissen aber damit entsprechend der Standards fast unbrauchbar in Abgrenzung der Emaille (Email) hält der Duden an einer Schreibweise fest: E-Mail. Für die Fehlermeldung wäre dann noch ein "Korrekte" Schreibweise-Hinweis gut und irgendwo im Readme, warum welche Standards dann so eng gesetzt werden sollen. Ich finde die Arbeit der Entwicklungsmenschen hier wirklich beeindruckend. Und möchte das eigentlich durch einen Einsatz würdigen. Daher die Bitte: E-Mail wäre besser. Das ist ein Verbesserungsvorschlag und keine Fehlermeldung. Ebenso der Hinweis das selbst bei der Schreibweise wie in der Fehlermeldung der Fehler noch angezeigt wird.
![Screenshot 2024-12-28 171741](https://github.com/user-attachments/assets/9cdeaedb-020b-4cd8-98a1-a2b3c25ad0c6)

**Comment by HansRoulade** [comment]
Da gehe ich prinzipiell mit - das lässt sich auch auf andere Felder ausweiten, wie z.B. `Telefon:` oder `Mobil:`.

Eventuelle leere Zeilenumbrüche dürfen ebenfalls nicht vorhanden sein.
