### ISSUE TITLE
Can't save a pdf with the exe version

### ISSUE THREAD

**Issue by maxik94** [lka/excel2zugferd#5]
Hey,
first off: 
I'm an enduser not a dev, so please be patient with my noob-ness. :-D
I downloaded the .exe on windows. I can startup the process, import a .xlsx, enter master data and click on save - but nothing happens?
No error, no new file, just ... nothing?

Where am I going wrong?

Could you tell me what the save option is ought to do, and if (as I believe at least) it is supposed to save the excelsheet+master data to the pdf, where is the pdf saved then?

Thanks so much in advance!

**Comment by maxik94** [comment]
thanks for the quick reply, however, I still can't really get it to work.

I edit the Masterdata (I can't define a path to the excel file here? However, I checked the button for attaching ZUGFeRD Data) and save it. It is saved whenever I restart the .exe, so I am pretty sure this is initialized as intended.
Then I choose the excelfile (the TestRechnung in this case), choose Rechnung2 sheet and try clicking save, but nothing is created - neither in the excel path nor in the path where TestRechnung is located.

**Comment by lka** [comment]
That‘s ok. The output must be „Rechnung2.pdf“ in the Directory where TestRechnung.xlsx exists. The directory must be writeable. I tested it with Desktop and subdirectories of „Dokumente“. If something goes wrong, then an error Message will be produced.

**Comment by maxik94** [comment]
Once again thanks for the fast reply.
Initially I used the portable version, now I tried the setup version - yet it yields the same result, independent on where the xlsx file is located (e.g., documents, desktop, D:, ...)

"To my understanding: you downloaded „setup_excel2zugferd.zip“ unzipped it and executed the setup file. Then generated a link from C:\Programme (x86)\Excel2Zugferd\excel2zugferd.exe anywhere you want to execute it (I used Desktop). Then started this program?"
Yes!

![image](https://github.com/user-attachments/assets/56f1e3ca-037d-4b6b-a7c6-56c9d6d12518)
I can press "Speichern" as often as I want to, nothing happens (I would reckon there would be a pop-up if it was un-/successful?).
I also tried changing masterdata, adding/removing the logo,...

**Comment by lka** [comment]
Please close the program and restart it again. Then select Excel-File without opening master data. Then double-click Rechnung2 or select Rechnung2 and then click on "Speichern".
I recognize the same behaviour when changing masterdata before selecting Excel-File... Nothing happens after pressing "Speichern".
Thanks for reporting the bug, I'll try to change it.

**Comment by maxik94** [comment]
Thanks again for your answer.
I tried exactly as you told me to - however, the outcome stays the same.. Doesn't seem to work on my Device. If it helps in troubleshooting: Win10, x64, 32gb RAM.
