### ISSUE TITLE
Kontonummer + Abspann

### ISSUE THREAD

**Issue by toteph42** [lka/excel2zugferd#7]
Hallo,

Kontonummer Stammdaten sollte dreizeilig sein:

`Name`
`IBAN`
`BIC`

wird aber derzeit nur zweizeilig akzeptiert und landet dann in falschen Feldern (1.Zeil=Kontoinhaber, 2.Zeile=IBAN). Getestet mit: https://xrechnung.rib.de/

Abspann (versucht mit 2-zeilig) wird nicht ausgegeben.

Gruß

**Comment by lka** [comment]
Ich habe ein Beispiel in die Dokumentation gepackt.

**Comment by toteph42** [comment]
Danke für die Doku. Jetzt sieht es besser aus, aber der Abspann wird nicht im PDF angezeigt. Validierung mit
https://www.ultramarinviewer.de/ funktioniert. 

Wenn ich über deinen Link gehe, dann lande ich bei https://www.portinvoice.com/. Dort gibt es jede Menge Meldungen:

Das XML ist nicht valide.
Profil: urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended
Bestandene Regeln: 95
Gescheiterte Regeln: 2

Details
Error
[BR-FXEXT-CO-11]-Absolute Value of (Sum of allowances on document level (BT-107) - Σ Document level allowance amounts (BT-92))<= 0,01 * Number of Document level allowance amounts (BT-92). [ID FX-SCH-A-000304] from /xslt/ZF_230/FACTUR-X_EXTENDED.xslt)
/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:SupplyChainTradeTransaction[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:ApplicableHeaderTradeSettlement[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]/*:SpecifiedTradeSettlementHeaderMonetarySummation[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]
Error
[BR-FXEXT-CO-12]-Absolute Value of (Sum of charges on document level (BT-108) - Σ Document level charge amounts (BT-99) - Σ Logistics Service fee amounts (BT-x-272))<= 0,01 * (Number of Document level charge amounts (BT-99) + Number of Logistics Service fee amounts (BT-X-272)). [ID FX-SCH-A-000305] from /xslt/ZF_230/FACTUR-X_EXTENDED.xslt)
/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:SupplyChainTradeTransaction[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:ApplicableHeaderTradeSettlement[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]/*:SpecifiedTradeSettlementHeaderMonetarySummation[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]

Das XML ist nicht valide.
Profil: urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended
Korrekte XML Struktur: Nein
Korrektes XML Schema: OK
Korrekte XML Namespaces: OK
Korrekte XML Kodierung: OK
Korrekte Code Listen: Nein
Gibt es Warnungen? Ja

Details
[VD-Valitool-14]-Der Namespace xmlns:qdt fehlt. Auch wenn dieser in der Instanzdatei nicht benötigt wird, sollte dieser gemäß Spezifikation angegeben werden.
[VD-Valitool-28]-Der Code >de< ist unzulässig
/rsm:CrossIndustryInvoice/rsm:ExchangedDocument/ram:LanguageID
[VD-Valitool-126]-Hinweis: Es wurde ein leeres Element übergeben z.B. .
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeDelivery
[VD-Valitool-22]-Die angegebene IBAN ist ungültig.
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount/ram:IBANID
[VD-Valitool-117]-Die Angabe des Zeitpunkts der Lieferung oder sonstigen Leistung der Rechnung muss mit einem Format (z.B. "102" für YYYYMMDD) qualifiziert werden. Diese Angabe fehlt.
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeDelivery/ram:ActualDeliverySupplyChainEvent/ram:OccurrenceDateTime/udt:DateTimeString/@format
[VD-Valitool-108]-Nach dem deutschen UStG §14 ist die Angabe des Zeitpunkts der Lieferung oder sonstigen Leistung eine Pflichtangabe. Die Angabe fehlt in der XML-Datei. Bitte prüfen Sie, ob Sie diese Angabe in Ihrer Geschäftsbeziehung machen müssen.
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeDelivery/ram:ActualDeliverySupplyChainEvent/ram:OccurrenceDateTime/udt:DateTimeString
[VD-Valitool-71]-Es konnten keine Angaben wie z.B. Geschäftsführer, Handelsregistereintrag oder ähnliches gefunden werden. (SubjectCode=REG). Bitte prüfen Sie, ob Sie diese Daten ggf. im Freitext angegeben haben oder diese Angaben für Ihre Rechnungsstellung nicht relevant sind.

Hier die Config.ini
[config.dmp](https://github.com/user-attachments/files/17291594/config.dmp)

Hier die erstellte Rechnung
[24001.pdf](https://github.com/user-attachments/files/17291551/24001.pdf)

**Comment by lka** [comment]
Für die weiteren Regelverstöße warte ich auf eine Reaktion der drafthorse library Entwickler.
